# Generated by Django 2.2.8 on 2019-12-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dest_short_desc',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_rating',
            field=models.FloatField(default=0),
        ),
    ]
