# Generated by Django 2.2.8 on 2019-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhuy', '0002_auto_20191212_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='', max_length=500)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('join_date', models.DateTimeField(verbose_name='Joined')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
