# Generated by Django 2.2.8 on 2019-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhuy', '0003_auto_20191212_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dest_country',
            field=models.CharField(default='', max_length=30),
        ),
    ]
