# Generated by Django 2.2.8 on 2019-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhuy', '0004_destination_dest_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_checkin',
            field=models.DateField(verbose_name='Check in'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_checkout',
            field=models.DateField(verbose_name='Check out'),
        ),
    ]
