# Generated by Django 2.2.8 on 2019-12-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhuy', '0005_auto_20191212_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_desc',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_image_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_short_desc',
            field=models.TextField(default='', max_length=100),
        ),
    ]
